/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AddEmployee {
    }
    interface AddProduct {
    }
    interface AddShop {
    }
    interface AddStock {
    }
    interface AdminDashboard {
    }
    interface AdminEmployees {
    }
    interface AdminGeneral {
    }
    interface AdminLogin {
    }
    interface AdminProducts {
    }
    interface AdminShops {
    }
    interface AppHome {
    }
    interface AppProfile {
        "name": string;
    }
    interface AppRoot {
    }
    interface AssignEmployee {
    }
    interface ChangePassword {
    }
    interface EditEmployee {
    }
    interface EditProduct {
    }
    interface EditShop {
    }
    interface ShopEmployeePopover {
    }
    interface ShopEmployees {
    }
    interface ShopSales {
    }
    interface ShopWaste {
    }
    interface ShopsPage {
    }
    interface SimsCart {
        "addToCart": (stock: any) => Promise<void>;
        "shopId": string;
        "toggle": () => Promise<void>;
    }
    interface SimsDashboard {
    }
    interface SimsGeneral {
    }
    interface SimsLogin {
    }
    interface SimsShop {
        "id": string;
    }
    interface SimsShops {
    }
    interface UserPopover {
    }
}
declare global {
    interface HTMLAddEmployeeElement extends Components.AddEmployee, HTMLStencilElement {
    }
    var HTMLAddEmployeeElement: {
        prototype: HTMLAddEmployeeElement;
        new (): HTMLAddEmployeeElement;
    };
    interface HTMLAddProductElement extends Components.AddProduct, HTMLStencilElement {
    }
    var HTMLAddProductElement: {
        prototype: HTMLAddProductElement;
        new (): HTMLAddProductElement;
    };
    interface HTMLAddShopElement extends Components.AddShop, HTMLStencilElement {
    }
    var HTMLAddShopElement: {
        prototype: HTMLAddShopElement;
        new (): HTMLAddShopElement;
    };
    interface HTMLAddStockElement extends Components.AddStock, HTMLStencilElement {
    }
    var HTMLAddStockElement: {
        prototype: HTMLAddStockElement;
        new (): HTMLAddStockElement;
    };
    interface HTMLAdminDashboardElement extends Components.AdminDashboard, HTMLStencilElement {
    }
    var HTMLAdminDashboardElement: {
        prototype: HTMLAdminDashboardElement;
        new (): HTMLAdminDashboardElement;
    };
    interface HTMLAdminEmployeesElement extends Components.AdminEmployees, HTMLStencilElement {
    }
    var HTMLAdminEmployeesElement: {
        prototype: HTMLAdminEmployeesElement;
        new (): HTMLAdminEmployeesElement;
    };
    interface HTMLAdminGeneralElement extends Components.AdminGeneral, HTMLStencilElement {
    }
    var HTMLAdminGeneralElement: {
        prototype: HTMLAdminGeneralElement;
        new (): HTMLAdminGeneralElement;
    };
    interface HTMLAdminLoginElement extends Components.AdminLogin, HTMLStencilElement {
    }
    var HTMLAdminLoginElement: {
        prototype: HTMLAdminLoginElement;
        new (): HTMLAdminLoginElement;
    };
    interface HTMLAdminProductsElement extends Components.AdminProducts, HTMLStencilElement {
    }
    var HTMLAdminProductsElement: {
        prototype: HTMLAdminProductsElement;
        new (): HTMLAdminProductsElement;
    };
    interface HTMLAdminShopsElement extends Components.AdminShops, HTMLStencilElement {
    }
    var HTMLAdminShopsElement: {
        prototype: HTMLAdminShopsElement;
        new (): HTMLAdminShopsElement;
    };
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {
    }
    var HTMLAppProfileElement: {
        prototype: HTMLAppProfileElement;
        new (): HTMLAppProfileElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLAssignEmployeeElement extends Components.AssignEmployee, HTMLStencilElement {
    }
    var HTMLAssignEmployeeElement: {
        prototype: HTMLAssignEmployeeElement;
        new (): HTMLAssignEmployeeElement;
    };
    interface HTMLChangePasswordElement extends Components.ChangePassword, HTMLStencilElement {
    }
    var HTMLChangePasswordElement: {
        prototype: HTMLChangePasswordElement;
        new (): HTMLChangePasswordElement;
    };
    interface HTMLEditEmployeeElement extends Components.EditEmployee, HTMLStencilElement {
    }
    var HTMLEditEmployeeElement: {
        prototype: HTMLEditEmployeeElement;
        new (): HTMLEditEmployeeElement;
    };
    interface HTMLEditProductElement extends Components.EditProduct, HTMLStencilElement {
    }
    var HTMLEditProductElement: {
        prototype: HTMLEditProductElement;
        new (): HTMLEditProductElement;
    };
    interface HTMLEditShopElement extends Components.EditShop, HTMLStencilElement {
    }
    var HTMLEditShopElement: {
        prototype: HTMLEditShopElement;
        new (): HTMLEditShopElement;
    };
    interface HTMLShopEmployeePopoverElement extends Components.ShopEmployeePopover, HTMLStencilElement {
    }
    var HTMLShopEmployeePopoverElement: {
        prototype: HTMLShopEmployeePopoverElement;
        new (): HTMLShopEmployeePopoverElement;
    };
    interface HTMLShopEmployeesElement extends Components.ShopEmployees, HTMLStencilElement {
    }
    var HTMLShopEmployeesElement: {
        prototype: HTMLShopEmployeesElement;
        new (): HTMLShopEmployeesElement;
    };
    interface HTMLShopSalesElement extends Components.ShopSales, HTMLStencilElement {
    }
    var HTMLShopSalesElement: {
        prototype: HTMLShopSalesElement;
        new (): HTMLShopSalesElement;
    };
    interface HTMLShopWasteElement extends Components.ShopWaste, HTMLStencilElement {
    }
    var HTMLShopWasteElement: {
        prototype: HTMLShopWasteElement;
        new (): HTMLShopWasteElement;
    };
    interface HTMLShopsPageElement extends Components.ShopsPage, HTMLStencilElement {
    }
    var HTMLShopsPageElement: {
        prototype: HTMLShopsPageElement;
        new (): HTMLShopsPageElement;
    };
    interface HTMLSimsCartElement extends Components.SimsCart, HTMLStencilElement {
    }
    var HTMLSimsCartElement: {
        prototype: HTMLSimsCartElement;
        new (): HTMLSimsCartElement;
    };
    interface HTMLSimsDashboardElement extends Components.SimsDashboard, HTMLStencilElement {
    }
    var HTMLSimsDashboardElement: {
        prototype: HTMLSimsDashboardElement;
        new (): HTMLSimsDashboardElement;
    };
    interface HTMLSimsGeneralElement extends Components.SimsGeneral, HTMLStencilElement {
    }
    var HTMLSimsGeneralElement: {
        prototype: HTMLSimsGeneralElement;
        new (): HTMLSimsGeneralElement;
    };
    interface HTMLSimsLoginElement extends Components.SimsLogin, HTMLStencilElement {
    }
    var HTMLSimsLoginElement: {
        prototype: HTMLSimsLoginElement;
        new (): HTMLSimsLoginElement;
    };
    interface HTMLSimsShopElement extends Components.SimsShop, HTMLStencilElement {
    }
    var HTMLSimsShopElement: {
        prototype: HTMLSimsShopElement;
        new (): HTMLSimsShopElement;
    };
    interface HTMLSimsShopsElement extends Components.SimsShops, HTMLStencilElement {
    }
    var HTMLSimsShopsElement: {
        prototype: HTMLSimsShopsElement;
        new (): HTMLSimsShopsElement;
    };
    interface HTMLUserPopoverElement extends Components.UserPopover, HTMLStencilElement {
    }
    var HTMLUserPopoverElement: {
        prototype: HTMLUserPopoverElement;
        new (): HTMLUserPopoverElement;
    };
    interface HTMLElementTagNameMap {
        "add-employee": HTMLAddEmployeeElement;
        "add-product": HTMLAddProductElement;
        "add-shop": HTMLAddShopElement;
        "add-stock": HTMLAddStockElement;
        "admin-dashboard": HTMLAdminDashboardElement;
        "admin-employees": HTMLAdminEmployeesElement;
        "admin-general": HTMLAdminGeneralElement;
        "admin-login": HTMLAdminLoginElement;
        "admin-products": HTMLAdminProductsElement;
        "admin-shops": HTMLAdminShopsElement;
        "app-home": HTMLAppHomeElement;
        "app-profile": HTMLAppProfileElement;
        "app-root": HTMLAppRootElement;
        "assign-employee": HTMLAssignEmployeeElement;
        "change-password": HTMLChangePasswordElement;
        "edit-employee": HTMLEditEmployeeElement;
        "edit-product": HTMLEditProductElement;
        "edit-shop": HTMLEditShopElement;
        "shop-employee-popover": HTMLShopEmployeePopoverElement;
        "shop-employees": HTMLShopEmployeesElement;
        "shop-sales": HTMLShopSalesElement;
        "shop-waste": HTMLShopWasteElement;
        "shops-page": HTMLShopsPageElement;
        "sims-cart": HTMLSimsCartElement;
        "sims-dashboard": HTMLSimsDashboardElement;
        "sims-general": HTMLSimsGeneralElement;
        "sims-login": HTMLSimsLoginElement;
        "sims-shop": HTMLSimsShopElement;
        "sims-shops": HTMLSimsShopsElement;
        "user-popover": HTMLUserPopoverElement;
    }
}
declare namespace LocalJSX {
    interface AddEmployee {
    }
    interface AddProduct {
    }
    interface AddShop {
    }
    interface AddStock {
    }
    interface AdminDashboard {
    }
    interface AdminEmployees {
    }
    interface AdminGeneral {
    }
    interface AdminLogin {
    }
    interface AdminProducts {
    }
    interface AdminShops {
    }
    interface AppHome {
    }
    interface AppProfile {
        "name"?: string;
    }
    interface AppRoot {
    }
    interface AssignEmployee {
    }
    interface ChangePassword {
    }
    interface EditEmployee {
    }
    interface EditProduct {
    }
    interface EditShop {
    }
    interface ShopEmployeePopover {
    }
    interface ShopEmployees {
    }
    interface ShopSales {
    }
    interface ShopWaste {
    }
    interface ShopsPage {
    }
    interface SimsCart {
        "onCartOperationDone"?: (event: CustomEvent<any>) => void;
        "shopId"?: string;
    }
    interface SimsDashboard {
    }
    interface SimsGeneral {
    }
    interface SimsLogin {
    }
    interface SimsShop {
        "id"?: string;
    }
    interface SimsShops {
    }
    interface UserPopover {
    }
    interface IntrinsicElements {
        "add-employee": AddEmployee;
        "add-product": AddProduct;
        "add-shop": AddShop;
        "add-stock": AddStock;
        "admin-dashboard": AdminDashboard;
        "admin-employees": AdminEmployees;
        "admin-general": AdminGeneral;
        "admin-login": AdminLogin;
        "admin-products": AdminProducts;
        "admin-shops": AdminShops;
        "app-home": AppHome;
        "app-profile": AppProfile;
        "app-root": AppRoot;
        "assign-employee": AssignEmployee;
        "change-password": ChangePassword;
        "edit-employee": EditEmployee;
        "edit-product": EditProduct;
        "edit-shop": EditShop;
        "shop-employee-popover": ShopEmployeePopover;
        "shop-employees": ShopEmployees;
        "shop-sales": ShopSales;
        "shop-waste": ShopWaste;
        "shops-page": ShopsPage;
        "sims-cart": SimsCart;
        "sims-dashboard": SimsDashboard;
        "sims-general": SimsGeneral;
        "sims-login": SimsLogin;
        "sims-shop": SimsShop;
        "sims-shops": SimsShops;
        "user-popover": UserPopover;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "add-employee": LocalJSX.AddEmployee & JSXBase.HTMLAttributes<HTMLAddEmployeeElement>;
            "add-product": LocalJSX.AddProduct & JSXBase.HTMLAttributes<HTMLAddProductElement>;
            "add-shop": LocalJSX.AddShop & JSXBase.HTMLAttributes<HTMLAddShopElement>;
            "add-stock": LocalJSX.AddStock & JSXBase.HTMLAttributes<HTMLAddStockElement>;
            "admin-dashboard": LocalJSX.AdminDashboard & JSXBase.HTMLAttributes<HTMLAdminDashboardElement>;
            "admin-employees": LocalJSX.AdminEmployees & JSXBase.HTMLAttributes<HTMLAdminEmployeesElement>;
            "admin-general": LocalJSX.AdminGeneral & JSXBase.HTMLAttributes<HTMLAdminGeneralElement>;
            "admin-login": LocalJSX.AdminLogin & JSXBase.HTMLAttributes<HTMLAdminLoginElement>;
            "admin-products": LocalJSX.AdminProducts & JSXBase.HTMLAttributes<HTMLAdminProductsElement>;
            "admin-shops": LocalJSX.AdminShops & JSXBase.HTMLAttributes<HTMLAdminShopsElement>;
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-profile": LocalJSX.AppProfile & JSXBase.HTMLAttributes<HTMLAppProfileElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "assign-employee": LocalJSX.AssignEmployee & JSXBase.HTMLAttributes<HTMLAssignEmployeeElement>;
            "change-password": LocalJSX.ChangePassword & JSXBase.HTMLAttributes<HTMLChangePasswordElement>;
            "edit-employee": LocalJSX.EditEmployee & JSXBase.HTMLAttributes<HTMLEditEmployeeElement>;
            "edit-product": LocalJSX.EditProduct & JSXBase.HTMLAttributes<HTMLEditProductElement>;
            "edit-shop": LocalJSX.EditShop & JSXBase.HTMLAttributes<HTMLEditShopElement>;
            "shop-employee-popover": LocalJSX.ShopEmployeePopover & JSXBase.HTMLAttributes<HTMLShopEmployeePopoverElement>;
            "shop-employees": LocalJSX.ShopEmployees & JSXBase.HTMLAttributes<HTMLShopEmployeesElement>;
            "shop-sales": LocalJSX.ShopSales & JSXBase.HTMLAttributes<HTMLShopSalesElement>;
            "shop-waste": LocalJSX.ShopWaste & JSXBase.HTMLAttributes<HTMLShopWasteElement>;
            "shops-page": LocalJSX.ShopsPage & JSXBase.HTMLAttributes<HTMLShopsPageElement>;
            "sims-cart": LocalJSX.SimsCart & JSXBase.HTMLAttributes<HTMLSimsCartElement>;
            "sims-dashboard": LocalJSX.SimsDashboard & JSXBase.HTMLAttributes<HTMLSimsDashboardElement>;
            "sims-general": LocalJSX.SimsGeneral & JSXBase.HTMLAttributes<HTMLSimsGeneralElement>;
            "sims-login": LocalJSX.SimsLogin & JSXBase.HTMLAttributes<HTMLSimsLoginElement>;
            "sims-shop": LocalJSX.SimsShop & JSXBase.HTMLAttributes<HTMLSimsShopElement>;
            "sims-shops": LocalJSX.SimsShops & JSXBase.HTMLAttributes<HTMLSimsShopsElement>;
            "user-popover": LocalJSX.UserPopover & JSXBase.HTMLAttributes<HTMLUserPopoverElement>;
        }
    }
}
